import { TraitCategory } from ".";

// Comprehensive trait data structure
export const traitCategories: TraitCategory[] = [
  {
    name: "Age",
    weight: 7,
    options: [
      { value: "15-year-old" },
      { value: "22-year-old" },
      { value: "35-year-old" },
      { value: "45-year-old" },
      { value: "67-year-old" },
      { value: "78-year-old" },
      { value: "elderly 82-year-old" },
      { value: "young 19-year-old" },
      { value: "middle-aged 52-year-old" },
      { value: "young adult" },
      { value: "adult in their 30s" },
      { value: "senior citizen" },
      { value: "centenarian" },
      { value: "adolescent" },
      { value: "college freshman" },
      { value: "recent retiree aged 65" },
      { value: "person in their late 40s" },
      { value: "person in their early 60s" },
      { value: "person in their late 20s" },
    ],
  },
  {
    name: "Occupation",
    weight: 6,
    options: [
      { value: "doctor" },
      { value: "teacher" },
      { value: "construction worker" },
      { value: "nurse" },
      { value: "firefighter" },
      { value: "artist" },
      { value: "engineer" },
      { value: "chef" },
      { value: "social worker" },
      { value: "mechanic" },
      { value: "librarian" },
      { value: "farmer" },
      { value: "scientist" },
      { value: "retail worker" },
      { value: "unemployed person" },
      { value: "retired person" },
      { value: "student" },
      { value: "police officer" },
      { value: "software developer" },
      { value: "musician" },
      { value: "taxi driver" },
      { value: "paramedic" },
      { value: "bartender" },
      { value: "professional athlete" },
      { value: "politician" },
      { value: "veterinarian" },
      { value: "delivery driver" },
      { value: "flight attendant" },
      { value: "plumber" },
      { value: "graphic designer" },
      { value: "childcare provider" },
      { value: "journalist" },
      { value: "electrician" },
      { value: "landscaper" },
      { value: "real estate agent" },
      { value: "security guard" },
    ],
  },
  {
    name: "Family Status",
    weight: 6,
    options: [
      { value: "devoted parent of three children" },
      { value: "single parent struggling to make ends meet" },
      { value: "loving grandparent" },
      { value: "expecting parent" },
      { value: "orphan with no living relatives" },
      { value: "caregiver for elderly parents" },
      { value: "eldest sibling supporting younger family members" },
      { value: "person with no close family ties" },
      { value: "recently married newlywed" },
      { value: "widow/widower living alone" },
      { value: "adoptive parent" },
      { value: "step-parent in a blended family" },
      { value: "person estranged from family" },
      { value: "grandparent raising grandchildren" },
      { value: "person with a large extended family" },
      { value: "childless by choice" },
      { value: "person with a newborn" },
      { value: "person supporting a sibling with special needs" },
      { value: "person recently reunited with birth family" },
      { value: "person with a family member overseas" },
      { value: "single child in a large family" },
      { value: "parent of twins" },
      { value: "person with adopted siblings" },
      { value: "person caring for a foster child" },
      { value: "recently divorced parent" },
      { value: "person with step-siblings" },
      { value: "person living with in-laws" },
      { value: "person with a blended family" },
      { value: "person supporting a cousin through college" },
      { value: "person with a military family member" },
    ],
  },
  {
    name: "Health Status",
    weight: 5,
    options: [
      { value: "person battling terminal cancer" },
      { value: "healthy individual in peak physical condition" },
      { value: "person with a disability who lives independently" },
      { value: "person recovering from a major surgery" },
      { value: "person with chronic but manageable diabetes" },
      { value: "someone dealing with depression" },
      { value: "person who recently overcame addiction" },
      { value: "individual with excellent mental health" },
      { value: "person requiring regular medical treatment" },
      { value: "someone with a rare genetic condition" },
      { value: "person with asthma" },
      { value: "individual with hearing impairment" },
      { value: "person with visual impairment" },
      { value: "person living with HIV" },
      { value: "person with mobility challenges" },
      { value: "person with a heart condition" },
      { value: "individual with chronic pain" },
      { value: "person with epilepsy" },
      { value: "person in cancer remission" },
      { value: "person with an autoimmune disorder" },
      { value: "person with a food allergy" },
      { value: "individual with PTSD" },
      { value: "person with a prosthetic limb" },
      { value: "person with high blood pressure" },
      { value: "individual with a recent sports injury" },
      { value: "person with a mild cognitive impairment" },
      { value: "person with a pacemaker" },
      { value: "individual with a chronic respiratory illness" },
      { value: "person with a recent concussion" },
      { value: "person with a history of migraines" },
    ],
  },
  {
    name: "Community Role",
    weight: 4,
    options: [
      { value: "respected community leader" },
      { value: "volunteer at local homeless shelter" },
      { value: "youth mentor and coach" },
      { value: "neighborhood watch coordinator" },
      { value: "person known for helping others" },
      { value: "local activist fighting for social justice" },
      { value: "someone who keeps to themselves" },
      { value: "pillar of the local religious community" },
      { value: "organizer of community events" },
      { value: "person struggling with social connections" },
      { value: "block association president" },
      { value: "community gardener" },
      { value: "school board member" },
      { value: "local business owner" },
      { value: "sports team coach" },
      { value: "neighborhood mediator" },
      { value: "food bank volunteer" },
      { value: "public library supporter" },
      { value: "animal shelter volunteer" },
      { value: "community choir member" },
      { value: "parent-teacher association member" },
      { value: "local historian" },
      { value: "community theater actor" },
      { value: "neighborhood clean-up organizer" },
      { value: "community newsletter editor" },
      { value: "local youth group leader" },
      { value: "community sports referee" },
      { value: "public park volunteer" },
      { value: "community art project coordinator" },
      { value: "neighborhood festival planner" },
    ],
  },
  {
    name: "Moral Standing",
    weight: 4,
    options: [
      { value: "person known for unwavering honesty" },
      {
        value: "individual who has made serious mistakes but learned from them",
      },
      { value: "someone who always puts others before themselves" },
      { value: "person with a complicated moral history" },
      { value: "individual admired for their integrity" },
      { value: "someone working to make amends for past wrongs" },
      { value: "person who struggles with ethical decisions" },
      { value: "individual known for their compassion" },
      { value: "someone who stands up for what's right" },
      { value: "person trying to turn their life around" },
      { value: "person who volunteers anonymously" },
      { value: "individual who returned a lost wallet" },
      { value: "person who forgave a major betrayal" },
      { value: "individual who speaks out against injustice" },
      { value: "person who donates time to charity" },
      { value: "individual who mentors troubled youth" },
      { value: "person who advocates for fairness" },
      { value: "individual who admits their faults" },
      { value: "person who stands up to bullies" },
      { value: "individual who supports ethical businesses" },
    ],
  },
  {
    name: "Financial Standing",
    weight: 3,
    options: [
      { value: "wealthy philanthropist" },
      { value: "person living paycheck to paycheck" },
      { value: "financially stable middle-class individual" },
      { value: "someone experiencing homelessness" },
      { value: "person who recently lost their home" },
      { value: "individual with significant debt" },
      { value: "person who donates regularly to charity" },
      { value: "someone saving for their children's future" },
      { value: "individual struggling with poverty" },
      { value: "person with modest but secure means" },
      { value: "person with a recent inheritance" },
      { value: "individual who won the lottery" },
      { value: "person with a successful side business" },
      { value: "individual who lost savings in a scam" },
      { value: "person who supports extended family financially" },
      { value: "individual with a high-paying job but high expenses" },
      { value: "person who invests in startups" },
      { value: "individual with a trust fund" },
      { value: "person who is a frugal saver" },
      { value: "individual who lives off the grid" },
    ],
  },
  {
    name: "Education",
    weight: 3,
    options: [
      { value: "PhD holder researching climate solutions" },
      { value: "high school dropout with street wisdom" },
      { value: "recent college graduate" },
      { value: "self-taught expert in their field" },
      { value: "person currently pursuing their GED" },
      { value: "skilled tradesperson with years of experience" },
      { value: "lifelong learner despite limited formal education" },
      { value: "university professor" },
      { value: "person with specialized technical training" },
      { value: "individual who values practical knowledge" },
      { value: "community college student" },
      { value: "person with a master's degree" },
      { value: "individual with a law degree" },
      { value: "person who attended vocational school" },
      { value: "individual with a scholarship" },
      { value: "person who is a published author" },
      { value: "individual who dropped out of college" },
      { value: "person with a background in the arts" },
      { value: "individual who is a certified technician" },
      { value: "person who is a language polyglot" },
    ],
  },
  {
    name: "Personality",
    weight: 3,
    options: [
      { value: "naturally optimistic and cheerful person" },
      { value: "quiet, thoughtful individual" },
      { value: "someone with an infectious laugh" },
      { value: "person who tends to worry excessively" },
      { value: "individual known for their quick wit" },
      { value: "someone who is incredibly patient" },
      { value: "person with a fiery temper but good heart" },
      { value: "naturally empathetic individual" },
      { value: "someone who is socially awkward but kind" },
      { value: "person with remarkable resilience" },
      { value: "person who is highly organized" },
      { value: "individual who is adventurous" },
      { value: "person who is introverted" },
      { value: "individual who is extroverted" },
      { value: "person who is a perfectionist" },
      { value: "individual who is spontaneous" },
      { value: "person who is highly creative" },
      { value: "individual who is detail-oriented" },
      { value: "person who is a natural leader" },
      { value: "individual who is very empathetic" },
    ],
  },
  {
    name: "Past Accomplishments",
    weight: 2,
    options: [
      { value: "former Olympic athlete" },
      { value: "person who saved lives during a natural disaster" },
      { value: "individual who overcame significant childhood trauma" },
      { value: "someone who built a successful business from nothing" },
      { value: "person who served their country in the military" },
      { value: "individual who invented something beneficial to society" },
      { value: "someone who raised millions for charity" },
      { value: "person who mentored countless young people" },
      { value: "individual who survived a life-threatening illness" },
      { value: "someone who made significant scientific discoveries" },
      { value: "person who completed a marathon" },
      { value: "individual who published a best-selling book" },
      { value: "person who won a national award" },
      { value: "individual who restored a historic building" },
      { value: "person who founded a community organization" },
      { value: "individual who overcame illiteracy" },
      { value: "person who rescued animals in need" },
      { value: "individual who taught themselves a new language" },
      { value: "person who completed a solo world trip" },
      { value: "individual who received a humanitarian award" },
    ],
  },
  {
    name: "Future Potential",
    weight: 2,
    options: [
      { value: "aspiring to become a doctor" },
      { value: "planning to start a family next year" },
      { value: "about to launch a nonprofit organization" },
      { value: "working toward a cure for a rare disease" },
      { value: "hoping to reconcile with estranged family" },
      { value: "planning to retire and travel the world" },
      { value: "studying to become a teacher" },
      { value: "working on a novel that could inspire others" },
      { value: "training for an important competition" },
      { value: "preparing to adopt children in need" },
      { value: "planning to start a business" },
      { value: "hoping to earn a degree" },
      { value: "training for a marathon" },
      { value: "preparing to move abroad" },
      { value: "aspiring to become an artist" },
      { value: "working toward financial independence" },
      { value: "hoping to buy a home" },
      { value: "planning to volunteer overseas" },
      { value: "studying for a major exam" },
      { value: "preparing to foster children" },
    ],
  },
  {
    name: "Dependents",
    weight: 2,
    options: [
      { value: "sole caregiver for disabled spouse" },
      { value: "person supporting elderly parents financially" },
      { value: "guardian of three young nephews" },
      { value: "caregiver for special needs child" },
      { value: "person caring for terminally ill partner" },
      { value: "foster parent to multiple children" },
      { value: "individual with no dependents" },
      { value: "caregiver for aging grandparents" },
      { value: "person supporting unemployed family members" },
      { value: "single guardian of younger siblings" },
      { value: "person with a dependent pet" },
      { value: "individual supporting a friend in need" },
      { value: "person caring for a neighbor's child" },
      { value: "individual with a dependent roommate" },
      { value: "person supporting a partner through school" },
      { value: "individual with a dependent parent-in-law" },
      { value: "person caring for a disabled sibling" },
      { value: "individual supporting a distant relative" },
      { value: "person with multiple dependents" },
      { value: "individual supporting a community member" },
    ],
  },
  {
    name: "Relationship Status",
    weight: 1,
    skipArticle: true,
    options: [
      { value: "happily married for 25 years" },
      { value: "recently divorced and rebuilding life" },
      { value: "in a loving relationship of 5 years" },
      { value: "single and content with independence" },
      { value: "widowed after losing spouse last year" },
      { value: "engaged to be married next month" },
      { value: "separated and working on reconciliation" },
      { value: "single parent dating again" },
      { value: "married but struggling with relationship" },
      { value: "lifelong bachelor/bachelorette by choice" },
      { value: "in a long-distance relationship" },
      { value: "recently started dating" },
      { value: "in an open relationship" },
      { value: "recently engaged" },
      { value: "in a polyamorous relationship" },
      { value: "single after a breakup" },
      { value: "remarried after divorce" },
      { value: "in a committed partnership" },
      { value: "widowed and dating again" },
      { value: "in a civil union" },
    ],
  },
  {
    name: "Criminal History",
    weight: 1,
    options: [
      { value: "person with a clean criminal record" },
      { value: "former convict who has turned life around" },
      { value: "individual with minor past legal troubles" },
      {
        value: "someone who served time for white-collar crime",
        skipArticle: true,
      },
      { value: "person wrongly convicted but later exonerated" },
      { value: "individual with drunk driving conviction from youth" },
      { value: "former gang member now working with at-risk youth" },
      { value: "person who spent years in prison but has reformed" },
      { value: "individual with history of civil disobedience for causes" },
      {
        value: "someone with juvenile record who became successful",
        skipArticle: true,
      },
      { value: "person with a history of petty theft" },
      { value: "individual who completed community service" },
      { value: "person with a restraining order in the past" },
      { value: "individual who was pardoned" },
      { value: "person with a history of traffic violations" },
      { value: "individual who testified as a witness" },
      { value: "person who was a victim of wrongful arrest" },
      { value: "individual with a sealed juvenile record" },
      { value: "person who advocates for criminal justice reform" },
      { value: "individual with a history of activism arrests" },
    ],
  },
  {
    name: "Special Circumstance",
    weight: 1,
    options: [
      { value: "person who just received life-changing news" },
      { value: "individual celebrating their wedding anniversary today" },
      {
        value: "someone rushing to donate bone marrow to save a life",
      },
      { value: "person carrying the cure for a deadly disease" },
      { value: "individual who just lost their job this morning" },
      { value: "someone on their way to adopt a child" },
      { value: "person carrying important evidence of corruption" },
      {
        value: "individual who just learned they're going to be a grandparent",
      },
      {
        value: "someone returning from visiting dying parent",
      },
      { value: "person who just graduated after years of study" },
      { value: "person about to propose marriage" },
      { value: "individual who just won a major award" },
      { value: "person who narrowly missed a flight" },
      { value: "individual who found a lost child" },
      { value: "person who just received a scholarship" },
      { value: "individual who is moving to a new country" },
      { value: "person who just survived an accident" },
      { value: "individual who is reuniting with a childhood friend" },
      { value: "person who just received a job offer" },
      { value: "individual who is about to become a parent" },
    ],
  },
];

export const englishNames: string[] = [
  "Aaron", "Abigail", "Adam", "Adrian", "Aimee", "Alan", "Albert", "Alexandra", "Alexis", "Alfie",
  "Alice", "Amelia", "Amy", "Andrew", "Angela", "Annabelle", "Anthony", "Archie", "Arthur", "Ashley",
  "Audrey", "Ava", "Bailey", "Benjamin", "Bernadette", "Bethany", "Bradley", "Brandon", "Brian", "Brooke",
  "Caleb", "Cameron", "Caroline", "Carter", "Catherine", "Charles", "Charlotte", "Chelsea", "Chloe", "Christian",
  "Christopher", "Clara", "Cody", "Colin", "Connor", "Courtney", "Craig", "Daisy", "Daniel", "David",
  "Deborah", "Declan", "Demi", "Diana", "Dominic", "Dylan", "Edward", "Eleanor", "Eli", "Elias",
  "Elizabeth", "Ella", "Ellie", "Emily", "Emma", "Erin", "Ethan", "Eva", "Evelyn", "Faye",
  "Felicity", "Finley", "Florence", "Frances", "Frank", "Freya", "Gabriella", "Georgia", "Grace", "Graham",
  "Gregory", "Hannah", "Harry", "Hayden", "Heather", "Helen", "Henry", "Holly", "Isaac", "Isabella",
  "Ivy", "Jack", "Jackson", "Jacob", "Jade", "James", "Jasmine", "Jason", "Jayden", "Jessica",
  "Joe", "John", "Jonathan", "Jordan", "Joseph", "Joshua", "Joyce", "Jude", "Julia", "Julian",
  "Justin", "Kaitlyn", "Karen", "Katherine", "Katie", "Kayla", "Keira", "Keith", "Kelly", "Kenneth",
  "Kevin", "Kian", "Kimberly", "Kyle", "Lacey", "Lauren", "Leah", "Leo", "Leon", "Lewis",
  "Liam", "Lily", "Lincoln", "Lisa", "Logan", "Louis", "Lucas", "Lucy", "Luke", "Lydia",
  "Madison", "Maisie", "Marc", "Marcus", "Margaret", "Maria", "Marianne", "Mark", "Marley", "Martin",
  "Mary", "Mason", "Matthew", "Max", "Megan", "Mia", "Michael", "Michelle", "Milo", "Molly",
  "Morgan", "Nathan", "Natalie", "Niamh", "Nicholas", "Nicole", "Nina", "Noah", "Oliver", "Olivia",
  "Owen", "Paige", "Pamela", "Patrick", "Paul", "Penny", "Peter", "Phoebe", "Poppy", "Rachel",
  "Ralph", "Rebecca", "Rhys", "Richard", "Riley", "Robert", "Robin", "Roger", "Rose", "Ross",
  "Ruby", "Ryan", "Sally", "Sam", "Samantha", "Samuel", "Sarah", "Scarlett", "Scott", "Sebastian",
  "Shannon", "Sharon", "Shaun", "Shawn", "Sheila", "Shelley", "Simon", "Sofia", "Sophia", "Stephen",
  "Steve", "Steven", "Summer", "Susan", "Suzanne", "Sydney", "Sylvia", "Tanya", "Taylor", "Teresa",
  "Terence", "Thomas", "Timothy", "Tina", "Todd", "Tom", "Tony", "Tracey", "Trevor", "Tyler",
  "Valerie", "Vanessa", "Victoria", "Vincent", "Violet", "Virginia", "Vivian", "Walter", "Warren", "Wayne",
  "Wendy", "Wesley", "Will", "William", "Willow", "Wyatt", "Zack", "Zara", "Zoe", "Zola",
  "Ada", "Alfie", "Amber", "Andrea", "Angus", "Annette", "Barnaby", "Barry", "Beatrice", "Bella",
  "Blanche", "Bobby", "Brenda", "Brian", "Bruce", "Byron", "Carol", "Carla", "Carmel", "Carrie",
  "Cassie", "Cathy", "Cecilia", "Celeste", "Chad", "Chantelle", "Cheryl", "Chris", "Christian", "Claire",
  "Clare", "Clementine", "Colleen", "Connie", "Conrad", "Constance", "Cora", "Corey", "Corinne", "Crystal",
  "Dale", "Daphne", "Darcy", "Darlene", "Darren", "Debra", "Denise", "Dennis", "Derek", "Dianne",
  "Don", "Donna", "Doreen", "Doris", "Douglas", "Edith", "Edna", "Elise", "Ellen", "Elsie",
  "Elton", "Esther", "Ethel", "Eugenia", "Ewan", "Fiona", "Gareth", "Gavin", "Gemma", "Geoffrey",
  "Gerald", "Geraldine", "Gloria", "Gordon", "Gwen", "Hayley", "Heidi", "Helena", "Howard", "Hugh",
  "Irene", "Iris", "Isla", "Ivan", "Jacqueline", "Jamie", "Jane", "Janet", "Janice", "Jared",
  "Jean", "Jenny", "Jeremy", "Jerry", "Jillian", "Joanne", "Jodie", "Joel", "Jody", "Johanna",
  "Johnny", "Jon", "Josephine", "Joy", "Jude", "Judith", "Judy", "Julianna", "Julie", "Justine",
  "Karl", "Kate", "Katy", "Kay", "Keith", "Kelly", "Ken", "Kerrie", "Kerry", "Kirsty",
  "Lana", "Larissa", "Laura", "Laurence", "Leanne", "Leigh", "Lester", "Lilian", "Lindsay", "Linda",
  "Lionel", "Lorraine", "Louise", "Lucinda", "Lynne", "Lynda", "Lynn", "Madeleine", "Madeline", "Maeve",
  "Mandy", "Marlene", "Maureen", "Melanie", "Melissa", "Meryl", "Michael", "Michele", "Miles", "Mona",
  "Monica", "Muriel", "Myra", "Nancy", "Naomi", "Neil", "Neville", "Nigel", "Norma", "Pam",
  "Pat", "Patricia", "Patrick", "Patsy", "Peggy", "Penelope", "Perry", "Philippa", "Phyllis", "Piers",
  "Prudence", "Queenie", "Quentin", "Raymond", "Regina", "Rex", "Rhoda", "Rita", "Rob", "Robin",
  "Rodney", "Ronald", "Ronnie", "Rosalie", "Rosemary", "Rowan", "Roxanne", "Russell", "Ruth", "Sabrina",
  "Sallyann", "Sandra", "Sandy", "Scott", "Sean", "Serena", "Shane", "Shirley", "Sidney", "Sonia",
  "Sophie", "Stacey", "Stella", "Stephanie", "Sue", "Sylvester", "Terri", "Theodore", "Theresa", "Toby",
  "Trudy", "Una", "Ursula", "Vera", "Veronica", "Vivienne", "Wanda", "Wendy", "Wilfred", "Winnie",
  "Yvonne", "Zoe"
];